repos:
- repo: https://github.com/psf/black
  rev: 22.1.0
  hooks:
  - id: black
    language_version: python3.9
- repo: https://github.com/pycqa/flake8
  rev: 4.0.1
  hooks:
    - id: flake8
      name: flake8 (black)
      additional_dependencies: [flake8-bugbear]
      args:
      # Black config
      - "--extend-ignore=E203"
      - "--max-line-length=88"
- repo: https://github.com/pycqa/isort
  rev: 5.10.1
  hooks:
    - id: isort
      name: isort (black)
      args:
      # Black config
      - "--profile=black"
      # So docker doesn't change file permissions
      - "--overwrite-in-place"